/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A bidirectional stream pair. */
export declare class NapiBiStream {
	/** Take the send stream. Can only be called once. */
	takeSend(): NapiSendStream;
	/** Take the recv stream. Can only be called once. */
	takeRecv(): NapiRecvStream;
}

/** A WebTransport client that can connect to servers. */
export declare class NapiClient {
	/** Create a client that validates server certificates against system root CAs. */
	static withSystemRoots(): NapiClient;
	/**
	 * Create a client that skips certificate verification entirely.
	 * WARNING: Only use for testing with self-signed certificates.
	 */
	static disableVerify(): NapiClient;
	/** Create a client that validates server certificates by SHA-256 hash. */
	static withCertificateHashes(hashes: Array<Buffer>): NapiClient;
	/** Connect to a WebTransport server at the given URL. */
	connect(urlStr: string, options?: NapiConnectOptions | undefined | null): Promise<NapiSession>;
}

/** A receive stream for reading data. */
export declare class NapiRecvStream {
	/** Read up to `max_size` bytes from the stream. Returns null on FIN. */
	read(maxSize: number): Promise<Buffer | null>;
	/** Tell the peer to stop sending with the given error code. */
	stop(code: number): Promise<void>;
}

/** A pending WebTransport session request from a client. */
export declare class NapiRequest {
	/** Get the URL of the CONNECT request. */
	get url(): Promise<string>;
	/** Accept the session with 200 OK. */
	ok(): Promise<NapiSession>;
	/** Reject the session with the given HTTP status code. */
	reject(status: number): Promise<void>;
}

/** A send stream for writing data. */
export declare class NapiSendStream {
	/** Write data to the stream. */
	write(data: Buffer): Promise<void>;
	/** Signal that no more data will be written. */
	finish(): Promise<void>;
	/** Abruptly reset the stream with an error code. */
	reset(code: number): Promise<void>;
	/** Set the priority of the stream. */
	setPriority(priority: number): Promise<void>;
}

/** A WebTransport server that accepts incoming sessions. */
export declare class NapiServer {
	/** Create a server bound to the given address with the given TLS certificate. */
	static bind(addr: string, certPem: Buffer, keyPem: Buffer): NapiServer;
	/** Accept the next incoming WebTransport session request. */
	accept(): Promise<NapiRequest | null>;
	/** Close the server, stopping it from accepting new connections. */
	close(): void;
}

/** An established WebTransport session. */
export declare class NapiSession {
	/** The subprotocol selected by the server during WT-Available-Protocols negotiation. */
	get protocol(): string | null;
	/** Accept an incoming unidirectional stream. */
	acceptUni(): Promise<NapiRecvStream>;
	/** Accept an incoming bidirectional stream. */
	acceptBi(): Promise<NapiBiStream>;
	/** Open a new unidirectional stream. */
	openUni(): Promise<NapiSendStream>;
	/** Open a new bidirectional stream. */
	openBi(): Promise<NapiBiStream>;
	/** Send a datagram. */
	sendDatagram(data: Buffer): void;
	/** Receive a datagram. */
	recvDatagram(): Promise<Buffer>;
	/** Get the maximum datagram size. */
	maxDatagramSize(): number;
	/** Close the session with a code and reason. */
	close(code: number, reason: string): void;
	/** Wait for the session to close, returning close info matching W3C WebTransportCloseInfo. */
	closed(): Promise<NapiCloseInfo>;
}

/** Options for connecting to a WebTransport server. */
export interface NapiConnectOptions {
	/** Subprotocols for WT-Available-Protocols negotiation. */
	protocols?: Array<string> | undefined | null;
}

/** Info about why a session was closed, matching W3C WebTransportCloseInfo. */
export interface NapiCloseInfo {
	closeCode: number;
	reason: string;
}
